### ISSUE TITLE
DTLS1.3 support

### ISSUE THREAD

**Issue by eliot4321** [eclipse-californium/californium#1337]
Hi, 

Does Californium support DTLS1.3? if not, is it expected to be supported any time soon?

Thanks in advance.

**Comment by boaks** [comment]
It is neither supported nor planed in the next months.

Though Californium is a open source project, contributions are very welcome. 

Californium supports DTLS 1.2 Connection ID. Using java 11 runitme, x25519 is added for ECDHE. If I get the time to do so, I would also try to implement ECDSA based on that curve and maybe TLS_???_CHACHA20_POLY1305_SHA256. But that depends on the time I'm able to spend into that.

**Comment by boaks** [comment]
I don't expect contribution for DTLS 1.3 "soon".

**Comment by sbernard31** [comment]
@boaks, is this still not planed at short/mid term ?

**Comment by boaks** [comment]
At least from my side not in short.

I consider, that using DTLS CID will provide already many benefits. With mbedTLS and tinyDtls there are already two client implementations, and at least my [Thingy:91](https://www.nordicsemi.com/Products/Development-hardware/Nordic-Thingy-91) runs not that bad with it.

I currently think more about implement [RFC 7924 - certificate caching](https://datatracker.ietf.org/doc/html/rfc7924), but that depends more on some decision out side of my responsibility. 

The amount of work for DTLS 1.3 is large. And AFAIK, only mbedTLS seems to offer that in short. Do you have any specific feature of DTLS 1.3 you consider to be high lighted? Faster handshakes seems for me not that important with DTLS CID (and cert. caching).

**Comment by boaks** [comment]
Maybe, I check, if bc has some functionality to use for short term.

**Comment by boaks** [comment]
Should I open this issue again? But from my experience, either I do it, or "nobody ;-)".

**Comment by sbernard31** [comment]
> The amount of work for DTLS 1.3 is large

I guess it.

>  And AFAIK, only mbedTLS seems to offer that in short.

AFIAK there is not so much DTLS 1.3 implementation. I also see that the [RFC-dtls13](https://datatracker.ietf.org/doc/draft-ietf-tls-dtls13/) is still a draft. 

> Do you have any specific feature of DTLS 1.3 you consider to be high lighted? 

Not really but we begin to detect some interest about (D)TLS 1.3 in general.
And so I just try to get some news from you about this. 

> Should I open this issue again?

This is up to you. 

Thx for all those information.
Let me know if (D)TLS 1.3 becomes a mid / short term subject for you.

**Comment by boaks** [comment]
> AFIAK there is not so much DTLS 1.3 implementation. I also see that the [RFC-dtls13](https://datatracker.ietf.org/doc/draft-ietf-tls-dtls13/) is still a draft.

The RFC9147 is in the editors queue (as RFC9146 also), and [mbedtls plans to support in in the near future](https://github.com/ARMmbed/mbedtls/issues/5443#issuecomment-1017379238).

> Not really but we begin to detect some interest about (D)TLS 1.3 in general.

Yep, but at least my feeling is, this is more for general interest than for a specific feature.  

> Let me know if (D)TLS 1.3 becomes a mid / short term subject for you.

Once I start with it, I will let you know.

**Comment by eabase** [comment]
@boaks 
@sbernard31 

>> I also see that the [RFC-dtls13](https://datatracker.ietf.org/doc/draft-ietf-tls-dtls13/) is still a draft.

> The RFC9147 is in the editors queue (as RFC9146 also) ...

Now, since April 2022, DTLS 1.3 is not longer a "draft", however, it's stated as "proposal", which I have asked to clarify here:

https://github.com/tlswg/dtls13-spec/issues/282

> this is more for general interest than for a specific feature.

Not anymore. People want 1.3 because of (at least) 3 main reasons:
- Substantial power saving when in deep sleep mode, nearly not possible in 1.2
- Substantial security improvements (removing insecure protocols)
- Zero touch provision support.

**Comment by boaks** [comment]
> Substantial power saving when in deep sleep mode, nearly not possible in 1.2

DTLS 1.2 Connection ID is exactly what's needed for that. I developed [zephyr-coaps-client](https://github.com/boaks/zephyr-coaps-client) with [Eclipse/tinydtls](https://github.com/eclipse/tinydtls). With that a Thingy:91 runs from the internal battery over more than 6 months exchanging every hour a message. DTLS 1.3 will not really improve that further.

> Substantial security improvements (removing insecure protocols)

Just configure the client and servers stack not to permit such "insecure protocols".
Or at least to prefer the secure ones.

> Zero touch provision support.

I'm not familiar with that.

DTLS 1.3 is for sure a good development. Unfortunately the industry have lost the interest to finance such developments. For Californium itself it's hard to make decision to add implementations, e.g. DTLS 1.3 and to keep the quality. It's a question of the trade-off. For sure there will be different opinions on that. On my view, it was mainly me who did the debugging and bug-fixing for the past 5 years and I'm not longer able to spend that huge amount of time doing so.

Therefore my focus is on using CoAP/DTLS 1.2 Connection ID and demonstrate, how products benefit from that. Let's see, if that brings back the interest.

**Comment by eabase** [comment]
Hi Achim, 
Yes, thanks for clarifying and updating. 

>  Zero touch provision support.
> ... I'm not familiar with that.

It's basically the same as *One-step device commissioning*. You put the SIM card in the device and power it on, and it works after you have registered the device IMEI with your IoT management provider.

**Comment by redoriental** [comment]
The current quic protocol seems to require dtls 1.3

**Comment by boaks** [comment]
AFAIK, I may be wrong, QUIC RFC 9100 comes with it's own security.

**Comment by redoriental** [comment]
Do you know "webtransport" is a transport tool on this browser. It is similar to "websocket" based on udp, and it is based on dtls 1.3 for the quic protocol

**Comment by boaks** [comment]
No, I don't know "webtransport".

**Comment by redoriental** [comment]
Well, my hopes of creating an http3 server have been dashed

**Comment by boaks** [comment]
> Well, my hopes of creating an http3 server have been dashed

Now I understand, you want DTLS 1.3 for HTTP3 . As I wrote, I think QUIC comes anyway with it's own security.

The point with DTLS 1.3 and Californium is simple, I tried to explain it above.
For a "hobby contribution" a DTLS 1.3 implementation will be quite time consuming.
And a "professional contribution" hasn't shown up for a couple of years.
With that, I'm happy to use a stable and mature DTLS 1.2 CID implementation.

**Comment by redoriental** [comment]
thank you，I know the meaning that you say

**Comment by yangyangliuli** [comment]
Hi boaks，

There are two problems:
1)Does californium support coap+DTLS1.2+session resumption now? If supported, what CMD is needed to start the server?
2)Does californium support coap+DTLS1.3 now? If supported, which ciphersuites should be used?

**Comment by boaks** [comment]
1) Yes. It is enabled by default, see [DTLS_SERVER_USE_SESSION_ID](https://github.com/eclipse-californium/californium/blob/main/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConfig.java#L405-L411).

2) No. For mbedTLS it was announced some time ago, but the last time I asked, I got the answer, that I'm welcome to implement it. 

`Plans`:
I'm not longer payed to work in open source. Therefore it's now a hobby project. My personal plan is to spend something as 4h (one afternoon) a week for Californium and tinydtls together. I don't think, that starting to implement DTLS 1.3 makes sense with that.
Out of that scope of that 4h I implement my idea of an [CoAP-S3-Proxy](https://github.com/boaks/californium/tree/add_s3_proxy) and improve my [cellular demo client](https://github.com/boaks/zephyr-coaps-client). With that, investing my own time in DTLS 1.3 doesn't make too much sense.

**Comment by yangyangliuli** [comment]
Ok, got it, thank you for your answer.

**Comment by boaks** [comment]
You're welcome.
Just to mention, because you ask about "session resumption", Californium supports [RFC 9146, DTLS 1.2 Connection ID](https://www.rfc-editor.org/info/rfc9146), which usually obsoletes session resumptions caused by ip-address changes.

**Comment by yangyangliuli** [comment]
Thanks for reminding me, my colleague has already encountered this problem.

**Comment by boaks** [comment]
Pretty long without any interest to contribute such an implementation.
Therefore I prefer to put it in hibernate. 
If someone wants to work on this, don't hesitate to leave a comment here.

**Comment by Arpan0995** [comment]
The standards picture has moved since this was hibernated, so leaving a comment as invited.

The IETF published RFC 9851 ("TLS 1.2 is in Feature Freeze") in July 2026, with the blunt statement that "PQC for TLS 1.2 will not be specified [...] at any time; anyone wishing to deploy PQC should expect to use TLS 1.3". The RFC scopes itself to TLS proper, not DTLS, but DTLS 1.2 ends up in the same place by a different route: the post-quantum hybrid groups (X25519MLKEM768 and friends, draft-ietf-tls-ecdhe-mlkem) are defined against the TLS 1.3 key_share exchange, and there is no proposal in the TLS WG to bring any PQ key establishment to the 1.2 handshake. Meanwhile NIST IR 8547 deprecates the classical asymmetric algorithms (ECDH, ECDSA, RSA) after 2030 and disallows them after 2035.

Put together: for CoAP over DTLS, quantum-resistant key establishment means DTLS 1.3. Scandium 3.14.0's key exchange surface is `XECDHECryptography.SupportedGroup`, the classical named curves, and `ProtocolVersion` has no 1.3, so there is nowhere for a PQ group to land today. The harvest-now-decrypt-later concern makes this a confidentiality issue on today's traffic, not just a 2035 deadline.

Since planning data is more useful than advocacy, here is what PQ over DTLS 1.3 would actually carry on the wire. Key shares for the X25519MLKEM768 hybrid group (the one browsers and OpenSSH converged on; the TLS draft is still in progress but the sizes are fixed by FIPS 203) are 1,216 bytes from the client, 1,120 back. Certificates I measured (DER, chain without trust anchor, EC keys in the classical case):

| | ECDSA P-256 | ML-DSA-44 | ML-DSA-65 |
|---|--:|--:|--:|
| 3-tier chain | 850 B | 8,043 B | 11,101 B |
| CertificateVerify signature | ~72 B | 2,420 B | 3,309 B |

So a certificate-mode server flight goes from roughly 1.1 KB (one datagram) to roughly 15.5 KB with ML-DSA-65, which is about 13 datagrams at the 1,280-byte IPv6 minimum MTU that constrained networks live on. Each lost datagram in that flight costs a handshake retransmission round, so loss amplification gets materially worse exactly where links are lossiest.

The more encouraging half: the urgent part (key exchange, because of harvest-now-decrypt-later) is cheap. A PSK plus hybrid-ML-KEM handshake carries about 2.3 KB of key-share material and no certificates, roughly two datagrams per flight, and RPK mode stays moderate too (an ML-DSA-65 SubjectPublicKeyInfo is about 2 KB). The expensive part, ML-DSA certificate chains, can lag behind on a separate timeline, and mitigation work exists there (the abridged-certificates approach was the only one that helped in my measurements; plain compression does almost nothing against ML-DSA signatures, which are incompressible). Measurements and harnesses: https://github.com/Arpan0995/pqc-cert-compression and https://github.com/Arpan0995/pqc-dual-family-kem

I am not in a position to volunteer a DTLS 1.3 implementation, so this is not that comment. But if this ever wakes up, I would be glad to help with the PQ side of it: sizing and fragmentation analysis against real Scandium flights, the hybrid key-share plumbing (I work with BC's ML-KEM at the low level), and review. And if there is appetite for an interim step short of 1.3, documenting the freeze and its consequence for Scandium users may itself be worth doing.

**Comment by boaks** [comment]
Just to mention:
I'm simply still not able to spend the required time.
If there is interest from others, please let us know,
