### ISSUE TITLE
RabbitMq server to a client with/without observer

### ISSUE THREAD

**Issue by noomio** [eclipse-californium/californium#2115]
Hi,

Currently we are using the coap server for the edge devices to communicate with our server. The cloud infrastructure relies on rabbit mq for message queuing. When the device sends a payload to the coap server that is then forwarded to a data processor and then to rabbit mq. 

Client initiated transactions  (NON and CON) work fine but we are having some issues with the observe and anything that is triggered from the server and needs to be sent to the edge device. FYI, I'm not the cloud developer.

The developer has got the observe sort of working but there are some issues with it.

My question is:

1. What is the best way for rabbitmq to communicate with the coap server?
3. Do we need to implement observe as if we know that a client is connected we can write to socket related to that device - how can this be done; I guess a list of connected clients is available?

Th

**Comment by boaks** [comment]
I'm not clear, which component runs where.

Does the coap server run in the cloud? Or on some gateway?

The problem is usually the IP traffic and the IP routes. If your peer has not static IP-address or the IP message passes a NAT, then the IP route back is in the very most cases "time limited". Nasty, for UDP this time is mostly much smaller than for TCP.
 
> 1 What is the best way for rabbitmq to communicate with the coap server?

I don't use rabbitmq and so don't have the experience. And I'm not sure, if I get the question. You use two protocols, coap and rabbitmq. So you need a "cross-proxy", which converts between the protocols. That proxy includes then a coap-server and communicates with the device via coap and with the other cloud components via rabbitmq. So I'm not sure, what you're really asking.

> a list of connected clients is available?

UDP is connection less. The device can be reached with the last reported IP-address. If that is static and no NATs are on your IP route, you can always sent a message. If your device has dynamic/changing IP-address or NATs are on your route, you must consider the "IP-adddress timeouts". It's not uncommon, that this timeout is even not defined. So try 30s and see if that works. So
"If your server receives a message from the client, you assume, that this client is then "connected" for about 30s".

**Comment by jvermillard** [comment]
Were you able to check Eclipse Hono? From a high-level point of view, Hono looks like it's doing what you try to do.

**Comment by noomio** [comment]
Thanks for the feedback.

For now we shall just use GET to consume messages that are left in the queue for the devices. 

We shall look at Hono also. Unfortunetly there is a legacy back end that we need to work with.
