### ISSUE TITLE
Extending InMemoryConnectionStore to add DTLS connection sharing between instances

### ISSUE THREAD

**Issue by cyril2maq** [eclipse-californium/californium#2118]
We face the same needs as described in #1484. 

Some of our clients does not enforce new handshake when their devices wake up; despite their IP address may have change - our LoadBalancer is IP-based.

We did analyze the DTLS CID LoadBalancer solution, but it does not fit our needs : we do not use kubernetes (for the auto-discovery), the persistency mechanism is sensitive to non-graceful shutdown; even with the BLUE/GREEN mechanism there will be some 'miss', and it is not compliant with auto-scaling (in case of decreasing the number of instances).

As a consequence we are implementing a redis-based connection store, which does answer to above limitations.

The idea is to extend the current InMemoryConnectionStore :

- storing the session in redis on put/updated method after calling super.put/update
- removing the session from redis on remove method after calling super.remove
- on get(ConnectionId cid) method : if super.get is empty (i.e. not in local cache), check on redis and restore the connection it is has been stored

(in order to avoid several instances to keep a specific CID connection info in their local cache - hence inconsisent -, we also handle a 'clear in-memory cache for CID=xxx' event consumed by other instances when a connection is restored from redis on an instance)

This implementation requires quite few lines of code.

We are aware it will use intensively redis and decrease DTLS communication performances.  

This solution does rely a lot on the current InMemoryConnectionStore implementation; nevertheless it only uses 'super.xxx' methods that are defined in the ResumptionSupportingConnectionStore interface.

We try to estimate if this approach is future proof - it is very sensitive to ResumptionSupportingConnectionStore interface / InMemoryConnectionStore implementation ; if there are some corner case where this could not work ?

Thanks a lot for any feedbacks 🙏

**Comment by boaks** [comment]
============================================================

- storing the session in redis on put/updated method after calling super.put/update
- removing the session from redis on remove method after calling super.remove
- on get(ConnectionId cid) method : if super.get is empty (i.e. not in local cache), check on redis and restore the connection it is has been stored

============================================================

Please note, there is a very fundamental difference between the `DTLSSession` and the `DTLSContext` associated with the `Connection`. 
In the far past, the idea was to share the `DTLSSession`. This is only accessed during the handshake and so the usage is very limited. It requires, that the device do frequently resumption handshakes.
To share the `Connection` or `DTLSContext` is ways more inefficient and sophisticated than the `DTLSSession`. Any access may change the "record sequence numbers state" and requires that to be synced. Otherwise the vulnerability for replay attack is increasing.

**Comment by cyril2maq** [comment]
Thank you a lot for taking time to answer.

> Do these device use DTLS CID? 

Yes.

> The cid-load-balancer approach was chosen

I fully understand and can't disagree. We just have some specific use cases, constraints and environment which lead us to evaluate alternative solutions.

> My concern with that solution is still, that this will be easily the main door for (D)DoS attacks

I agree. We also manage other types of connectivity and we face similar challenges. We use firewall protection and in-memory rate limiting to mitigate the risks. Regarding DTLS callflows, don't we face the same (D)DoS risks with abbreviated handshake and shared `DTLSSession` (discussed in #1345) ?

> Do you have already numbers for that slowdown?

Not for now, but when we will have some, I will share it here.

> Would it be possible for you consider to use InMemoryReadWriteLockConnectionStore? 

Thanks, we did miss this class ! We will use it.

> Overall, I don't expect this changing 

That is a valuable information for us.

> ... but the future is unwritten

Otherwise, our job would be much more boring 😉

**Comment by boaks** [comment]
Any progress?
Any interface or API extension required?
Or can we close it?

**Comment by cyril2maq** [comment]
We did a Redis-based implementation and our functional tests are OK with current API.
We still need to measure performance impact; but this is beyond this specific issue.
So yes we can close it; thanks again for your support !

**Comment by boaks** [comment]
Thanks!

**Comment by boaks** [comment]
Just to mention, maybe it helps:

Californium has a user-space simple [NAT](https://github.com/eclipse-californium/californium/tree/main/cf-utils/cf-nat). I use this frequently to test network issues caused by address changes, also under load.

And Californium has a "benchmark-client" in [cf-extplugtest-client](https://github.com/eclipse-californium/californium/tree/main/demo-apps/cf-extplugtest-client). I use this to test "handovers" or "failovers" under load.

The critical points in your approach will be, when the real communication changes faster than you align the states. Or on breakdown, when the real communication is ahead of the state wrote to the cache. I guess, both tools maybe useful for tests.

**Comment by sbernard31** [comment]
@cyril2maq 

> We still need to measure performance impact; but this is beyond this specific issue.

Do you have any news about that :point_up:

**Comment by cyril2maq** [comment]
Regarding performances, we did 2 kinds of tests: 

- 'overall' performance tests with this Redis ConnectionStore implementation, i.e. test cases including other middlewares (database and event bus). For instance 'register + send' use case. As other middleware calls take much more time than Redis to handle the flow triggered by any LwM2M message (like storing data, sending a status update event...); the impact of this InMemory to Redis implementation is quite non existent (about 1%).

- FOTA use case which will heavily use the ConnectionStore and no other time consuming process. In this case the difference is very noticeable, we got a factor 10x in our test environment.

**Comment by boaks** [comment]
Thanks for the update!

> including other middlewares ...  As other middleware calls take much more time

Depending on the other middlewares, that's also my experience.

>  factor 10x 

OK. AFAIK, (but I may be wrong) redis is TCP baesd? Do you forward the "sequence number changes" directly or "delayed in bulk"?

**Comment by cyril2maq** [comment]
> AFAIK, (but I may be wrong) redis is TCP based?

Yes, Redis is TCP based.

> Do you forward the "sequence number changes" directly or "delayed in bulk"?

For now we use a simple 'direct' simpler implementation. Indeed the delayed bulk mechanism would increase performance in this context, we'll keep that in mind if we encounter performance issue in the future !

**Comment by boaks** [comment]
Thanks a lot for the very interesting and useful update about the achieved performance!

**Comment by cyril2maq** [comment]
No problem to share, but what kind of sharing ?
The Redis implementation we wrote is linked to our software implementation. Several elements are very specific; e.g. 
- it is Spring-ified 
- we implemented metrics for cache hit/miss
- we use a 'notificationService' to send event on bus for other instances to be aware that the 'owner' instance of a specific cid has changed (and thus remove from local cache this cid in all other instances)

**Comment by sbernard31** [comment]
I was thinking about sharing the code as  copy/past of the class or a link to public repository which contains it but I had in mind that this was "just" a `ConnectionStore` based on **Redis**.

**Comment by cyril2maq** [comment]
You are right, this is not just a "RedisConnectionStore"; it is more a "InMemoryWithRedisFallbackConnectionStore" :
- it extends InMemoryReadWriteLockConnectionStore (thx @boaks for the hint)
- when we need to retrieve a cid; we just retrieve it from inMemory BUT if it is not present in memory (meaning another instance got it) then we retrieve it from redis (and tell other instances to remove it from their local cache)
- when updating a connection, we still update it in memory (by calling super.update(...) ) then we also update it in Redis

This is this updating part which is costly; and 90% useless (if you use a sticky proxy) as we will not read the result from redis because it will already be in memory of the instance. Hence @boaks  suggestion to store it in redis with a bulk/delayed mechanism (and only write once even if a cid had several updates during this delayed period).

**Comment by boaks** [comment]
> BUT if it is not present in memory (meaning another instance got it) then we retrieve it from redis

;-(.

Maybe you write me an e-mail and I write you my opinion back.

**Comment by jvermillard** [comment]
One way to achieve this is not to store the connection in Redis but if you don't have the connection locally, ask the node that has the connection to serialize the connection, get it, and restore it in the node receiving the connection.
You can use this:
https://github.com/eclipse-californium/californium/blob/c2a93bdd7a7f3428f6894a631b039db89edb0320/scandium-core/src/main/java/org/eclipse/californium/scandium/DtlsBindingPreprocessingConnector.java

No LB, no slow writing every connection change to redis, no K8S :)

**Comment by boaks** [comment]
Just to mention:
If someone likes, we may extend the [wiki](https://github.com/eclipse-californium/californium/wiki/DTLS-1.2-connection-ID-based-load-balancer) with some new pages containing your proposals and experience. 
AFAIK at least @jvermillard should be able to create pages, or?
If you, @cyril2maq , don't have the permission, then write the page here and I copy it to the wiki.

**Comment by jvermillard** [comment]
I have seen it 'working' at scale with Redis for storing the mapping between CID/client and the node IP address.
If you can't use direct IP addressing, you can still use Redis pub/sub to replace it (e.g. one topic per node and one topic for response), it should be quick enough. Of course, you should manage the timeout and shutdown, (in AWS environment you can use the various lifecycle events). But in the end, the performance impact is only a couple of milliseconds at the handshake and not every-packets (which not a problem because we are talking to high latency devices)
