### ISSUE TITLE
Observation option removed from block2 request

### ISSUE THREAD

**Issue by louis-hochart** [eclipse-californium/californium#2277]
Hello,
I'm working with leshan server v1.5.0, which works with californium 2.8.0

We are encountering an error when communicating with a device : 
**1. the server makes an observation request to the client**

[o.e.c.core.network.BaseMatcher - registerObserve()] - registering observe request CON-GET    MID=20136, Token=null, OptionSet={"Observe":0, "Uri-Path":["35251","0"]}, no payload

**2. the client respons with a block2 response, with block #0**
[o.e.c.core.network.UdpMatcher - receiveResponse()] - received response ACK-2.05   MID=20136, Token=DBF94429865D7654, OptionSet={"Observe":0, "Block2":"(szx=6/1024, m=true, num=0)", "Size2":1138},
[o.e.c.c.n.stack.BlockwiseLayer - handleBlock2Response()] - processing incoming block2 response [num=0]: ACK-2.05   MID=20136, Token=DBF94429865D7654, OptionSet={"Observe":0, "Block2":"(szx=6/1024, m=true, num=0)", "Size2":1138},

**3. server then requests the block #1**
[o.e.c.c.n.stack.BlockwiseLayer - requestNextBlock()] - requesting next Block2 [num=1]: CON-GET    MID=   -1, Token=null, OptionSet={"Uri-Path":["35251","0"], "Block2":"(szx=6/1024, m=false, num=1)"}, no payload
**but removes the observation option from the request**
[o.e.c.core.network.Exchange - setCurrentRequest()] - Exchange[L209] replace CON-GET    MID=20136, Token=DBF94429865D7654, OptionSet={"Observe":0, "Uri-Path":["35251","0"]}, acked no payload by CON-GET    MID=   -1, Token=null, OptionSet={"Uri-Path":["35251","0"], "Block2":"(szx=6/1024, m=false, num=1)"}, no payload
[o.e.c.c.n.stack.BlockwiseLayer - requestNextBlock()] - requesting next Block2 [num=1]: CON-GET    MID=   -1, Token=null, OptionSet={"Uri-Path":["35251","0"], "Block2":"(szx=6/1024, m=false, num=1)"}, no payload

**4. the client then responds a code 4.02 - Bad options because he expects the observation option to be present**

I found the code responsible for the removal of the observation option.

https://github.com/eclipse-californium/californium/blob/2.8.0/californium-core/src/main/java/org/eclipse/californium/core/network/stack/BlockwiseLayer.java
line 
1213 // make sure NOT to use Observe for block 
1214 block.getOptions().removeObserve();

Is this client behaviour expected ?

Thanks

**Comment by boaks** [comment]
See [RFC7959, page 27](https://www.rfc-editor.org/rfc/rfc7959#page-27).

The GET request, which establish the observation contains the "observe 0/empty".
The "retrieval of remaining blocks" not.

> but removes the observation option from the request

Yes, because RFC7959 specifies it in that way.

> Is this client behaviour expected ?

Not if the client complies with RFC7959, as you can see in that example of the RFC7959.

Which device-client implementation do you use? Is that a "up-to-date" one?

**Comment by giuseppe-melis** [comment]
Hi Achim,
I see the Figure 12 on RFC, but I don't find the real sentence reporting _"The "retrieval of remaining blocks" not."_
I find only _"the resulting block-wise transfer is as in Figure 4 and has therefore been left out"_ but it doesn't say clearly that the GET request must or mustn't report the Observe tag.
I think this detail is not defined at 100%: what do you think about?

Anyway, my LwM2M server reports the Observe=0 in the GET Block 1 and my client expects it, but leshan server v1.5.0/californium 2.8.0 doesn't report it, so different behaviours...

![image](https://github.com/user-attachments/assets/b5baa15a-4c92-419c-a78d-9e3b9e97a6f2)

**Comment by boaks** [comment]
You don't want to write, which server or device implementation you are using? 

If you have doubts about the interpretation of an RFC, it will be better to move your questions to a IETF mailing list. For CoAP that's the core-group and that group also uses [corrclar issues](https://github.com/core-wg/corrclar) for such questions. That ensures also, that the interpretation is in line with many other implementations.

> but it doesn't say clearly that the GET request must or mustn't report the Observe tag.

```
  CLIENT  SERVER
         |      |
         +----->|     Header: GET 0x41011636
         | GET  |      Token: 0xfb
         |      |   Uri-Path: status-icon
         |      |    Observe: (empty)
...
         |      |  (Retrieval of remaining blocks)
         |      |
         +----->|     Header: GET 0x41011637
         | GET  |      Token: 0xfc
         |      |   Uri-Path: status-icon
         |      |     Block2: 1/0/128
```

If it would be a MUST, the GET for Block2 1 would be wrong. There is just no need for that information a observe option will carry. The client already knows from the notify, that a new version of the resource is available. It doesn't make a difference, if the resource is read, because the client received a notification about the change or for other reasons. It would be the same resource, at least as long as the ETAG is the same.

**Comment by giuseppe-melis** [comment]
Sorry Achim,
I'm application engineer and I don't know the source of my LwM2M client and server, I should ask to R&D...anyway it could be an internal development.

I could raise a question to the core-group, even if you already provided a reliable description.
Sometimes the specs are a bit incomplete and leave space to interpretations, so I was checking it's the case.
Thanks a lot

**Comment by boaks** [comment]
> I'm application engineer and I don't know the source of my LwM2M client and server, I

No, no real need for that. 

> I could raise a question to the core-group, even if you already provided a reliable description.

I guess you will benefit from an answer there once you want to convince the device manufacturer to adapt.

> Sometimes the specs are a bit incomplete and leave space to interpretations, so I was checking it's the case.

That's true.

**Comment by boaks** [comment]
I guess, It's OK to close this one?

**Comment by giuseppe-melis** [comment]
yes, for me.
I don't know if it's ok for Louis

**Comment by louis-hochart** [comment]
Yes, thanks for your help @boaks 
I'm closing it
